# we want to install apache2 and php on a host server

- name: apache2 and php installation
  hosts: php-server
  become: true
  tasks:
    - name: update php server
      command: apt update


    - name: upgrade php server
      command: apt upgrade -y

    - name: install apache2
      command: apt install apache2 -y

    - name: start apache server
      service:
        name: apache2
        enabled: true
        state: started

    - name: set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos

    - name: php prerequisites
      command: apt install apt-transport-https lsb-release software-properties-common ca-certificates -y

    - name: install php repository
      command: add-apt-repository ppa:ondrej/php -y

    - name: install php
      command: apt install php7.4 -y

